# Generated by Django 5.1.7 on 2025-06-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_delete_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
