# Generated by Django 5.2.1 on 2025-06-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_issues_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='user_name',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='issue_type',
            field=models.CharField(choices=[('bug', 'Bug Report'), ('inappropriate', 'Inappropriate Content'), ('feature', 'Feature Request'), ('performance', 'Performance Issue'), ('accessibility', 'Accessibility Issue'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='issue_screenshots/'),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reported_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
