# Generated by Django 5.1.7 on 2025-05-14 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationFoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Grains & Bread', 'Grains & Bread'), ('Protein', 'Protein & Meat'), ('Prepared Meals', 'Prepared Meals'), ('Canned Goods', 'Canned Goods'), ('Other', 'Other')], max_length=50)),
                ('image', models.ImageField(upload_to='donation_food_posts/')),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_food_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Grains & Bread', 'Grains & Bread'), ('Protein', 'Protein & Meat'), ('Prepared Meals', 'Prepared Meals'), ('Canned Goods', 'Canned Goods'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Completed', 'Completed')], default='Available', max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_posts/')),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Expired', 'Expired')], default='Available', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.foodpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('Selangor', 'Selangor'), ('Kuala Lumpur', 'Kuala Lumpur'), ('Penang', 'Penang'), ('Johor', 'Johor'), ('Sabah', 'Sabah'), ('Sarawak', 'Sarawak')], max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_shares/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
