# Generated by Django 5.1.7 on 2025-05-14 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_create_donationfoodpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationfoodpost',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Completed', 'Completed')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='ClaimedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_foods', to=settings.AUTH_USER_MODEL)),
                ('food_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='community.donationfoodpost')),
            ],
        ),
    ]
