# Generated by Django 5.1.7 on 2025-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_donationfoodpost_status_claimedfood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='claimer',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='foodpost',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='foodshare',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.DeleteModel(
            name='FoodPost',
        ),
        migrations.DeleteModel(
            name='FoodShare',
        ),
    ]
